#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 26 14:45:14 2018

@author: brandonmcclung
"""

import pickle
import ASOS_stn
stn = pickle.load(open('../Data/pickles/obj_test.p','rb'))